### ISSUE TITLE
Outdated resume

### ISSUE THREAD

**Issue by JMdoubleU** [DanTheManGude/DanTheManGude.github.io#1]
[DanGudeResume.pdf](https://github.com/DanTheManGude/DanTheManGude.github.io/blob/cb2a486dc91effa374e94f2d5469f4b8e9a1d074/assets/DanGudeResume.pdf)

**Comment by DanTheManGude** [comment]
Closing this in favor of https://github.com/DanTheManGude/DanTheManGude.github.io/issues/2 to lump many outdated items into one issue.
